scrape_configs:
  - job_name: 'cockroachdb'
    scrape_interval: 10s
    metrics_path: '/_status/vars'
    scheme: 'http'
    tls_config:
      insecure_skip_verify: true

    static_configs:
    - targets: ['roach1:8080', 'roach2:8080', 'roach3:8080']
      labels:
        cluster: 'my-cockroachdb-cluster'
